// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtcurxcphfddzytrjgtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0Y3VyeGNwaGZkZHp5dHJqZ3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjM2NzIsImV4cCI6MjA1ODM5OTY3Mn0.aJ8Xt8Xs9BvdAbh9XEQaJGZv9wtxoA0p6KTw0dv5yZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);